name: npm test

on:
  push:
    branches: ["main"]
    paths:
      [
        "*.ts",
        "jest.config.js?(on)",
        "package-lock.json",
        ".github/workflows/npm-test.yml",
      ]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [lts/*, latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js @ ${{ matrix.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.version }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Install cached dependencies
        if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: npm i

      - name: Run tests
        run: npm test
