name: publish code coverage

on:
  push:
    branches: ["main"]
    paths:
      [
        "**.ts",
        "jest.config.js*",
        ".github/workflows/publish-code-coverage.yml",
      ]
  workflow_dispatch:

jobs:
  publish-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js @ lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-lts/*-build-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Generate code coverage reports
        run: npm test -- --coverage
        continue-on-error: true

      - name: Publish code coverage to codecov 🚀
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: true
